[build]
publish = "prod/wwwroot"

command = "dotnet workload install wasm-tools ; dotnet publish \"Portfolio/Portfolio.Website/Portfolio.Website.csproj\" -c Release -o release"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
