[build]
publish = "dev/wwwroot"

command = "dotnet workload install wasm-tools ; dotnet publish \"Portfolio/Portfolio.Website/Portfolio.Website.csproj\" -c Release -o dev"orkload install wasm-tools ; dotnet publish \"Portfolio/Portfolio.Website/Portfolio.Website.csproj\" -c Release -o prod"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
